name: todo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  cupertino_icons:
  dio:
  mobx:
  flutter_mobx:
  go_router:
  http:
  dartz:
  get_it:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen:
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/montserrat/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
            weight: 400
          - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
            weight: 600

